<a href="https://colab.research.google.com/github/MonicaPatibandla/Machine-Learning/blob/main/ML_Task_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from prettytable import PrettyTable
import matplotlib.pyplot as plt

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)

# Initialize the Decision Tree classifier
dtc = DecisionTreeClassifier(random_state=42)

# Fit the Decision Tree model on the training data
dtc.fit(X_train, y_train)

# Take the first 10 instances from the dataset
first_10_instances = heart_df.iloc[:10]

# Create a table to display results
result_table = PrettyTable()
result_table.field_names = ["Instance", "Naive Bayes Accuracy", "Decision Tree Accuracy"]

# Initialize lists to store accuracies for plotting
nb_accuracies = []
dt_accuracies = []

# Function to calculate accuracy for a single instance
def calculate_instance_accuracy(instance, model, X_test, y_test):
    # Append the instance to the test set
    X_test_instance = pd.concat([X_test, instance[features].to_frame().T], ignore_index=True)
    y_test_instance = np.append(y_test, instance[target])
    # Calculate accuracy
    return model.score(X_test_instance, y_test_instance)

# Iterate over the first 10 instances
for i in range(len(first_10_instances)):
    instance = first_10_instances.iloc[i]
    nb_accuracy = calculate_instance_accuracy(instance, gnb, X_test, y_test)
    dt_accuracy = calculate_instance_accuracy(instance, dtc, X_test, y_test)
    result_table.add_row([i+1, f"{nb_accuracy:.4f}", f"{dt_accuracy:.4f}"])
    nb_accuracies.append(nb_accuracy)
    dt_accuracies.append(dt_accuracy)

# Print the result table
print(result_table)

# Visualize the accuracies
instances = range(1, len(first_10_instances) + 1)

plt.figure(figsize=(12, 6))

# Plot Naive Bayes accuracies
plt.subplot(1, 2, 1)
plt.bar(instances, nb_accuracies, color='blue', alpha=0.7)
plt.title('Naive Bayes Accuracy')
plt.xlabel('Instance')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.xticks(instances)

# Plot Decision Tree accuracies
plt.subplot(1, 2, 2)
plt.bar(instances, dt_accuracies, color='green', alpha=0.7)
plt.title('Decision Tree Accuracy')
plt.xlabel('Instance')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.xticks(instances)

plt.tight_layout()
plt.show()


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from prettytable import PrettyTable
import matplotlib.pyplot as plt

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)

# Initialize the Decision Tree classifier
dtc = DecisionTreeClassifier(random_state=42)

# Fit the Decision Tree model on the training data
dtc.fit(X_train, y_train)

# Take the first 10 instances from the dataset
first_10_instances = heart_df.iloc[:10]

# Create a table to display results
result_table = PrettyTable()
result_table.field_names = ["Instance", "Naive Bayes Accuracy", "Decision Tree Accuracy"]

# Initialize lists to store accuracies for plotting
nb_accuracies = []
dt_accuracies = []

# Function to calculate accuracy for a single instance
def calculate_instance_accuracy(instance, model, X_test, y_test):
    # Append the instance to the test set
    X_test_instance = pd.concat([X_test, instance[features].to_frame().T], ignore_index=True)
    y_test_instance = np.append(y_test, instance[target])
    # Calculate accuracy
    return model.score(X_test_instance, y_test_instance)

# Iterate over the first 10 instances
for i in range(len(first_10_instances)):
    instance = first_10_instances.iloc[i]
    nb_accuracy = calculate_instance_accuracy(instance, gnb, X_test, y_test)
    dt_accuracy = calculate_instance_accuracy(instance, dtc, X_test, y_test)
    result_table.add_row([i+1, f"{nb_accuracy:.4f}", f"{dt_accuracy:.4f}"])
    nb_accuracies.append(nb_accuracy)
    dt_accuracies.append(dt_accuracy)

# Print the result table
print(result_table)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Compute and print the confusion matrices
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
conf_matrix_dtc = confusion_matrix(y_test, y_pred_dtc)

print("\nConfusion Matrix for Gaussian Naive Bayes:")
print(conf_matrix_nb)

print("\nConfusion Matrix for Decision Tree Classifier:")
print(conf_matrix_dtc)


+----------+----------------------+------------------------+
| Instance | Naive Bayes Accuracy | Decision Tree Accuracy |
+----------+----------------------+------------------------+
|    1     |        0.8370        |         0.7391         |
|    2     |        0.8261        |         0.7391         |
|    3     |        0.8370        |         0.7391         |
|    4     |        0.8370        |         0.7391         |
|    5     |        0.8370        |         0.7391         |
|    6     |        0.8370        |         0.7391         |
|    7     |        0.8370        |         0.7391         |
|    8     |        0.8370        |         0.7283         |
|    9     |        0.8370        |         0.7391         |
|    10    |        0.8370        |         0.7391         |
+----------+----------------------+------------------------+

Confusion Matrix for Gaussian Naive Bayes:
[[36  5]
 [10 40]]

Confusion Matrix for Decision Tree Classifier:
[[32  9]
 [15 35]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from prettytable import PrettyTable
import matplotlib.pyplot as plt

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)

# Initialize the Decision Tree classifier
dtc = DecisionTreeClassifier(random_state=42)

# Fit the Decision Tree model on the training data
dtc.fit(X_train, y_train)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Compute and print the confusion matrices for multiclass classification
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
conf_matrix_dtc = confusion_matrix(y_test, y_pred_dtc)

print("\nConfusion Matrix for Gaussian Naive Bayes:")
print(conf_matrix_nb)

print("\nConfusion Matrix for Decision Tree Classifier:")
print(conf_matrix_dtc)



Confusion Matrix for Gaussian Naive Bayes:
[[36  5]
 [10 40]]

Confusion Matrix for Decision Tree Classifier:
[[32  9]
 [15 35]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)

# Initialize the Decision Tree classifier
dtc = DecisionTreeClassifier(random_state=42)

# Fit the Decision Tree model on the training data
dtc.fit(X_train, y_train)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Compute the confusion matrices for each model
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
conf_matrix_dtc = confusion_matrix(y_test, y_pred_dtc)

# Get the unique class labels
class_labels = np.unique(y)

print("\nConfusion Matrices for Gaussian Naive Bayes:")
for i, label in enumerate(class_labels):
    print(f"\nClass {label} Confusion Matrix:")
    matrix = np.zeros((2, 2), dtype=int)
    matrix[0, 0] = conf_matrix_nb[i, i]  # True Positives for this class
    matrix[0, 1] = conf_matrix_nb[:, i].sum() - conf_matrix_nb[i, i]  # False Positives
    matrix[1, 0] = conf_matrix_nb[i, :].sum() - conf_matrix_nb[i, i]  # False Negatives
    matrix[1, 1] = conf_matrix_nb.sum() - (matrix[0, 0] + matrix[0, 1] + matrix[1, 0])  # True Negatives
    print(matrix)

print("\nConfusion Matrices for Decision Tree Classifier:")
for i, label in enumerate(class_labels):
    print(f"\nClass {label} Confusion Matrix:")
    matrix = np.zeros((2, 2), dtype=int)
    matrix[0, 0] = conf_matrix_dtc[i, i]  # True Positives for this class
    matrix[0, 1] = conf_matrix_dtc[:, i].sum() - conf_matrix_dtc[i, i]  # False Positives
    matrix[1, 0] = conf_matrix_dtc[i, :].sum() - conf_matrix_dtc[i, i]  # False Negatives
    matrix[1, 1] = conf_matrix_dtc.sum() - (matrix[0, 0] + matrix[0, 1] + matrix[1, 0])  # True Negatives
    print(matrix)



Confusion Matrices for Gaussian Naive Bayes:

Class 0 Confusion Matrix:
[[36 10]
 [ 5 40]]

Class 1 Confusion Matrix:
[[40  5]
 [10 36]]

Confusion Matrices for Decision Tree Classifier:

Class 0 Confusion Matrix:
[[32 15]
 [ 9 35]]

Class 1 Confusion Matrix:
[[35  9]
 [15 32]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)

# Initialize the Decision Tree classifier
dtc = DecisionTreeClassifier(random_state=42)

# Fit the Decision Tree model on the training data
dtc.fit(X_train, y_train)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Get the unique class labels
class_labels = np.unique(y)

print("\nOne-vs-Rest Confusion Matrices for Gaussian Naive Bayes:")
for label in class_labels:
    print(f"\nClass {label} vs Rest Confusion Matrix:")
    # Convert the target and predictions to binary (one-vs-rest)
    y_test_binary = (y_test == label).astype(int)
    y_pred_nb_binary = (y_pred_nb == label).astype(int)

    # Compute the confusion matrix
    conf_matrix_nb = confusion_matrix(y_test_binary, y_pred_nb_binary)

    print(conf_matrix_nb)

print("\nOne-vs-Rest Confusion Matrices for Decision Tree Classifier:")
for label in class_labels:
    print(f"\nClass {label} vs Rest Confusion Matrix:")
    # Convert the target and predictions to binary (one-vs-rest)
    y_test_binary = (y_test == label).astype(int)
    y_pred_dtc_binary = (y_pred_dtc == label).astype(int)

    # Compute the confusion matrix
    conf_matrix_dtc = confusion_matrix(y_test_binary, y_pred_dtc_binary)

    print(conf_matrix_dtc)



One-vs-Rest Confusion Matrices for Gaussian Naive Bayes:

Class 0 vs Rest Confusion Matrix:
[[40 10]
 [ 5 36]]

Class 1 vs Rest Confusion Matrix:
[[36  5]
 [10 40]]

One-vs-Rest Confusion Matrices for Decision Tree Classifier:

Class 0 vs Rest Confusion Matrix:
[[35 15]
 [ 9 32]]

Class 1 vs Rest Confusion Matrix:
[[32  9]
 [15 35]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the classifiers
gnb = GaussianNB()
dtc = DecisionTreeClassifier(random_state=42)

# Fit the models on the training data
gnb.fit(X_train, y_train)
dtc.fit(X_train, y_train)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Function to predict and print confusion matrix for a specific feature
def print_feature_confusion_matrix(feature, model, X_test, y_test, model_name):
    print(f"\nConfusion Matrix for '{feature}' (using {model_name}):")

    # Use the model to predict the target values (not the feature values)
    y_pred = model.predict(X_test) # Change here to predict target

    # Compute the confusion matrix using the true target values and predicted target values
    conf_matrix = confusion_matrix(y_test, y_pred) # Change here to use y_test

    print(conf_matrix)

# List of features to generate confusion matrices for
features_to_compare = features.copy()

# Generate confusion matrices for each feature vs. rest of the features
for feature in features_to_compare:
    print_feature_confusion_matrix(feature, gnb, X_test, y_test, "Gaussian Naive Bayes")
    print_feature_confusion_matrix(feature, dtc, X_test, y_test, "Decision Tree")


Confusion Matrix for 'age' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'age' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'sex' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'sex' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'cp' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'cp' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'trestbps' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'trestbps' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'chol' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'chol' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'fbs' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'fbs' (using Decision Tree):
[[32  9]
 [15 35]]

Confusion Matrix for 'restecg' (using Gaussian Naive Bayes):
[[36  5]
 [10 40]]

Confusion Matrix for 'rest

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv('/content/diabetes.csv')

# Check for missing values
print("Missing values:\n", data.isnull().sum())

# Define features (X) and target (y)
X = data.drop('Outcome', axis=1)
y = data['Outcome']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the models
nb_model = GaussianNB()
dt_model = DecisionTreeClassifier(random_state=42)

# Train the models
nb_model.fit(X_train, y_train)
dt_model.fit(X_train, y_train)

# Make predictions
nb_predictions = nb_model.predict(X_test)
dt_predictions = dt_model.predict(X_test)

# Function to compute and display confusion matrix in tabular format for each feature
def confusion_matrix_for_attributes(model_name, y_true, y_pred, X_test):
    metrics_dict = {}

    for feature in X_test.columns:
        print(f"\nConfusion Matrix for {feature} against the rest ({model_name}):")

        # Compute the confusion matrix
        cm = confusion_matrix(y_true, y_pred)

        # Create a DataFrame for better visualization
        cm_df = pd.DataFrame(cm, index=['Actual 0', 'Actual 1'], columns=['Predicted 0', 'Predicted 1'])

        # Calculate and store metrics for the feature
        metrics_dict[feature] = {
            'Accuracy': accuracy_score(y_true, y_pred),
            'Precision (Macro)': precision_score(y_true, y_pred, average='macro'),
            'Recall (Macro)': recall_score(y_true, y_pred, average='macro'),
            'F1 Score (Macro)': f1_score(y_true, y_pred, average='macro'),
            'Precision (Weighted)': precision_score(y_true, y_pred, average='weighted'),
            'Recall (Weighted)': recall_score(y_true, y_pred, average='weighted'),
            'F1 Score (Weighted)': f1_score(y_true, y_pred, average='weighted')
        }

        # Print the confusion matrix
        print(cm_df)

        # Visualize the confusion matrix using a heatmap
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
        plt.title(f"Confusion Matrix for {feature} ({model_name})")
        plt.show()

    return metrics_dict

# Function to display metrics for each feature in tabular format
def display_metrics_table(model_name, metrics_dict):
    metrics_df = pd.DataFrame(metrics_dict).T
    print(f"\nPerformance Metrics Table for {model_name}:")
    print(metrics_df)

# Get confusion matrices and metrics for Naive Bayes
nb_metrics = confusion_matrix_for_attributes("Naive Bayes", y_test, nb_predictions, X_test)

# Get confusion matrices and metrics for Decision Tree
dt_metrics = confusion_matrix_for_attributes("Decision Tree", y_test, dt_predictions, X_test)

# Display metrics in tabular format
display_metrics_table("Naive Bayes", nb_metrics)
display_metrics_table("Decision Tree", dt_metrics)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load the heart dataset
file_path = 'heart.csv'
heart_df = pd.read_csv(file_path)

# Select features and target
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
target = 'target'

# Handle missing values by filling them with the mean of the column
for feature in features:
    heart_df[feature].fillna(heart_df[feature].mean(), inplace=True)

# Define the feature matrix and target vector
X = heart_df[features]
y = heart_df[target]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the classifiers
gnb = GaussianNB()
dtc = DecisionTreeClassifier(random_state=42)

# Fit the models on the training data
gnb.fit(X_train, y_train)
dtc.fit(X_train, y_train)

# Predict the target values for the test set using both models
y_pred_nb = gnb.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

# Function to compute and display confusion matrix in tabular format for each feature
def confusion_matrix_for_attributes(model_name, y_true, y_pred, X_test):
    metrics_dict = {}

    for feature in X_test.columns:
        print(f"\nConfusion Matrix for {feature} against the rest ({model_name}):")

        # Compute the confusion matrix
        cm = confusion_matrix(y_true, y_pred)

        # Create a DataFrame for better visualization
        cm_df = pd.DataFrame(cm, index=['Actual 0', 'Actual 1'], columns=['Predicted 0', 'Predicted 1'])

        # Calculate and store metrics for the feature
        metrics_dict[feature] = {
            'Accuracy': accuracy_score(y_true, y_pred),
            'Precision (Macro)': precision_score(y_true, y_pred, average='macro'),
            'Recall (Macro)': recall_score(y_true, y_pred, average='macro'),
            'F1 Score (Macro)': f1_score(y_true, y_pred, average='macro'),
            'Precision (Weighted)': precision_score(y_true, y_pred, average='weighted'),
            'Recall (Weighted)': recall_score(y_true, y_pred, average='weighted'),
            'F1 Score (Weighted)': f1_score(y_true, y_pred, average='weighted')
        }

        # Print the confusion matrix
        print(cm_df)

        # Visualize the confusion matrix using a heatmap
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
        plt.title(f"Confusion Matrix for {feature} ({model_name})")
        plt.show()

    return metrics_dict

# Function to display metrics for each feature in tabular format
def display_metrics_table(model_name, metrics_dict):
    metrics_df = pd.DataFrame(metrics_dict).T
    print(f"\nPerformance Metrics Table for {model_name}:")
    print(metrics_df)

# Get confusion matrices and metrics for Naive Bayes
nb_metrics = confusion_matrix_for_attributes("Naive Bayes", y_test, nb_predictions, X_test)

# Get confusion matrices and metrics for Decision Tree
dt_metrics = confusion_matrix_for_attributes("Decision Tree", y_test, dt_predictions, X_test)

# Display metrics in tabular format
display_metrics_table("Naive Bayes", nb_metrics)
display_metrics_table("Decision Tree", dt_metrics)
